appName = "chat_room"

[mysql]
host = "127.0.0.1"
name = "chat"
user = "root"
password = "root"
port = 3306
tablePrefix = ""

[log]
level = "debug"
path = "logs/chat.log"

[staticPath]
filePath = "web/static/file/"
avatarPath = "web/static/file/avatar/"


[msgChannelType]
channelType = "gochannel"

kafkaHosts = "kafka:9092"
kafkaTopic = "go-chat-message"

[JwtToken]
tokenExpireTime = 120
secretKey = "5bAq6LcAkVh2xPGbYjvXpJiK5zWTg7EnDmFfytQsRcL9uIvG4zWSHabT6N3drM8KJU1qLpP2oF7G9eR5tSvNYCk"